name: Test Code
on: push
jobs:
  test-code-job:
   runs-on: ubuntu-latest
   steps:
    - name: Get code
      uses: actions/checkout@v4.1.1 # "uses" betyder att vi kör en action, inte ett command. "Checkout"-actionen laddar ner koden till maskinen
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8'
    - name: Install dependencies
      run: dotnet restore
    - name: Build app
      run: dotnet build --no-restore
    - name: Test app
      run: dotnet test --no-restore --verbosity normal
    - name: Post issue
      if: failure()
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ secrets.TOKEN }}
        title: Tests failed!
        body: Some of the tests didn't pass, fix pls