name: Test Code
on: push
jobs:
  test-code-job:
   runs-on: ubuntu-latest
   steps:
    - name: Get code
      uses: actions/checkout@v4.1.1 # "uses"" betyder att vi kör en action, inte ett command. "Checkout"-actionen laddar ner koden till maskinen